[phases.setup]
nixPkgs = ['python312', 'python312Packages.pip', 'python312Packages.virtualenv']

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  '/opt/venv/bin/pip install --upgrade pip',
  '/opt/venv/bin/pip install -r requirements.txt'
]

[phases.build]
cmds = []

[start]
cmd = '/opt/venv/bin/python -m gunicorn --bind 0.0.0.0:$PORT app:app --timeout 300'
