[phases.setup]
nixPkgs = ['python312', 'python312Packages.pip']

[phases.install]
cmds = [
  'pip install --user --upgrade pip',
  'pip install --user -r requirements.txt'
]

[phases.build]
cmds = []

[start]
cmd = 'python -m gunicorn --bind 0.0.0.0:$PORT app:app --timeout 300'
