[phases.setup]
nixPkgs = ['python312', 'python312Packages.pip', 'python312Packages.virtualenv']

[phases.install]
cmds = [
  'python -m venv venv',
  '. venv/bin/activate && pip install --upgrade pip',
  '. venv/bin/activate && pip install -r requirements.txt'
]

[phases.build]
cmds = []

[start]
cmd = '. venv/bin/activate && gunicorn --bind 0.0.0.0:$PORT app:app --timeout 300'
